version: "0.0.1"
services:
    nodejs: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 ermegilius/nodejs:0.0.1 bin/sh
        container_name: nodejs
        image: ermegilius/nodejs:0.0.1
        build: ./nodejs
        working_dir: /work
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes:
            - .:/nodejs/src/:/work
        ports:
            - "5002:5000"
